"""initial tables

Revision ID: 2241fcf04e20
Revises: 
Create Date: 2025-04-11 23:13:26.646091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2241fcf04e20'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estados',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estados_ejemplares',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('libros',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('autor', sa.String(length=100), nullable=True),
    sa.Column('editorial', sa.String(length=100), nullable=True),
    sa.Column('genero', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('miembros',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ejemplares',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('libro_id', sa.UUID(), nullable=False),
    sa.Column('codigo_interno', sa.String(length=50), nullable=False),
    sa.Column('estado_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['estado_id'], ['estados_ejemplares.id'], ),
    sa.ForeignKeyConstraint(['libro_id'], ['libros.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_interno')
    )
    op.create_table('prestamos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('miembro_id', sa.UUID(), nullable=False),
    sa.Column('ejemplar_id', sa.UUID(), nullable=False),
    sa.Column('estado_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['ejemplar_id'], ['ejemplares.id'], ),
    sa.ForeignKeyConstraint(['estado_id'], ['estados.id'], ),
    sa.ForeignKeyConstraint(['miembro_id'], ['miembros.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fechas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('prestamo_id', sa.UUID(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('fecha_devolucion', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['prestamo_id'], ['prestamos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historial',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('prestamo_id', sa.UUID(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['prestamo_id'], ['prestamos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('multas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('prestamo_id', sa.UUID(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('pagada', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['prestamo_id'], ['prestamos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('renovaciones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('prestamo_id', sa.UUID(), nullable=False),
    sa.Column('fecha_renovacion', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['prestamo_id'], ['prestamos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('renovaciones')
    op.drop_table('multas')
    op.drop_table('historial')
    op.drop_table('fechas')
    op.drop_table('prestamos')
    op.drop_table('ejemplares')
    op.drop_table('miembros')
    op.drop_table('libros')
    op.drop_table('estados_ejemplares')
    op.drop_table('estados')
    # ### end Alembic commands ###
